development:
  cloud_name: "domj9asek"
  api_key: "385838226674614"
  api_secret: "_DWnhg6-CvkD6KYJwYNleqap6m4"
  secure: true

production:
  cloud_name: "domj9asek"
  api_key: "385838226674614"
  api_secret: "_DWnhg6-CvkD6KYJwYNleqap6m4"
  secure: true
